/* SPDX-License-Identifier: MIT */
/*
 * Compile-time checks of the kernel ABI this library depends on: the ioctl
 * request value of every bridge ID it issues, the input and output sizes
 * the pvrsrvkm dispatch handlers copy, the client structure layouts callers
 * read, and the PVRSRV_ERROR values the library returns. A configuration
 * macro in srv_um_config.h that diverges from the kernel module shifts one
 * of these and fails the build.
 */
#include "srv_um_priv.h"

#include <stddef.h>

#include "pvrversion.h"

#define SRV_ABI_BRIDGE(id, value) \
	_Static_assert((PVRSRV_BRIDGE_##id) == (value), #id " request value")

#define SRV_ABI_SIZE(type, size) \
	_Static_assert(sizeof(type) == (size), "sizeof " #type)

#define SRV_ABI_OFFSET(type, member, offset) \
	_Static_assert(offsetof(type, member) == (offset), #type "." #member)

/* Bridge request values: _IOWR('g', index, PVRSRV_BRIDGE_PACKAGE). */
SRV_ABI_SIZE(PVRSRV_BRIDGE_PACKAGE, 28);
SRV_ABI_BRIDGE(UM_KM_COMPAT_CHECK,		0xc01c6700u);
SRV_ABI_BRIDGE(ENUM_DEVICES,			0xc01c6701u);
SRV_ABI_BRIDGE(ACQUIRE_DEVICEINFO,		0xc01c6702u);
SRV_ABI_BRIDGE(CREATE_DEVMEMCONTEXT,		0xc01c6704u);
SRV_ABI_BRIDGE(DESTROY_DEVMEMCONTEXT,		0xc01c6705u);
SRV_ABI_BRIDGE(GET_DEVMEM_HEAPINFO,		0xc01c6706u);
SRV_ABI_BRIDGE(ALLOC_DEVICEMEM,			0xc01c6707u);
SRV_ABI_BRIDGE(FREE_DEVICEMEM,			0xc01c6708u);
SRV_ABI_BRIDGE(MHANDLE_TO_MMAP_DATA,		0xc01c670cu);
SRV_ABI_BRIDGE(CONNECT_SERVICES,		0xc01c670du);
SRV_ABI_BRIDGE(DISCONNECT_SERVICES,		0xc01c670eu);
SRV_ABI_BRIDGE(MAP_DEV_MEMORY,			0xc01c6715u);
SRV_ABI_BRIDGE(UNMAP_DEV_MEMORY,		0xc01c6716u);
SRV_ABI_BRIDGE(EXPORT_DEVICEMEM,		0xc01c6719u);
SRV_ABI_BRIDGE(RELEASE_MMAP_DATA,		0xc01c671au);
SRV_ABI_BRIDGE(MAP_DEV_MEMORY_2,		0xc01c671cu);
SRV_ABI_BRIDGE(EXPORT_DEVICEMEM_2,		0xc01c671du);
SRV_ABI_BRIDGE(MAP_ION_HANDLE,			0xc01c671eu);
SRV_ABI_BRIDGE(UNMAP_ION_HANDLE,		0xc01c671fu);
SRV_ABI_BRIDGE(MAPPHYSTOUSERSPACE,		0xc01c6723u);
SRV_ABI_BRIDGE(UNMAPPHYSTOUSERSPACE,		0xc01c6724u);
SRV_ABI_BRIDGE(GET_MISC_INFO,			0xc01c6727u);
SRV_ABI_BRIDGE(MAP_DEVICECLASS_MEMORY,		0xc01c672au);
SRV_ABI_BRIDGE(UNMAP_DEVICECLASS_MEMORY,	0xc01c672bu);
SRV_ABI_BRIDGE(ENUM_CLASS,			0xc01c672cu);
SRV_ABI_BRIDGE(OPEN_DISPCLASS_DEVICE,		0xc01c672du);
SRV_ABI_BRIDGE(CLOSE_DISPCLASS_DEVICE,		0xc01c672eu);
SRV_ABI_BRIDGE(ENUM_DISPCLASS_FORMATS,		0xc01c672fu);
SRV_ABI_BRIDGE(ENUM_DISPCLASS_DIMS,		0xc01c6730u);
SRV_ABI_BRIDGE(GET_DISPCLASS_INFO,		0xc01c6732u);
SRV_ABI_BRIDGE(CREATE_DISPCLASS_SWAPCHAIN,	0xc01c6733u);
SRV_ABI_BRIDGE(DESTROY_DISPCLASS_SWAPCHAIN,	0xc01c6734u);
SRV_ABI_BRIDGE(SET_DISPCLASS_DSTRECT,		0xc01c6735u);
SRV_ABI_BRIDGE(SET_DISPCLASS_SRCRECT,		0xc01c6736u);
SRV_ABI_BRIDGE(SET_DISPCLASS_DSTCOLOURKEY,	0xc01c6737u);
SRV_ABI_BRIDGE(SET_DISPCLASS_SRCCOLOURKEY,	0xc01c6738u);
SRV_ABI_BRIDGE(GET_DISPCLASS_BUFFERS,		0xc01c6739u);
SRV_ABI_BRIDGE(SWAP_DISPCLASS_TO_BUFFER,	0xc01c673au);
SRV_ABI_BRIDGE(SWAP_DISPCLASS_TO_BUFFER2,	0xc01c673bu);
SRV_ABI_BRIDGE(SWAP_DISPCLASS_TO_SYSTEM,	0xc01c673cu);
SRV_ABI_BRIDGE(OPEN_BUFFERCLASS_DEVICE,		0xc01c673du);
SRV_ABI_BRIDGE(CLOSE_BUFFERCLASS_DEVICE,	0xc01c673eu);
SRV_ABI_BRIDGE(GET_BUFFERCLASS_INFO,		0xc01c673fu);
SRV_ABI_BRIDGE(GET_BUFFERCLASS_BUFFER,		0xc01c6740u);
SRV_ABI_BRIDGE(WRAP_EXT_MEMORY,			0xc01c6741u);
SRV_ABI_BRIDGE(UNWRAP_EXT_MEMORY,		0xc01c6742u);
SRV_ABI_BRIDGE(INITSRV_CONNECT,			0xc01c6747u);
SRV_ABI_BRIDGE(INITSRV_DISCONNECT,		0xc01c6748u);
SRV_ABI_BRIDGE(EVENT_OBJECT_WAIT,		0xc01c6749u);
SRV_ABI_BRIDGE(EVENT_OBJECT_OPEN,		0xc01c674au);
SRV_ABI_BRIDGE(EVENT_OBJECT_CLOSE,		0xc01c674bu);
SRV_ABI_BRIDGE(CREATE_SYNC_INFO_MOD_OBJ,	0xc01c674cu);
SRV_ABI_BRIDGE(DESTROY_SYNC_INFO_MOD_OBJ,	0xc01c674du);
SRV_ABI_BRIDGE(MODIFY_PENDING_SYNC_OPS,		0xc01c674eu);
SRV_ABI_BRIDGE(MODIFY_COMPLETE_SYNC_OPS,	0xc01c674fu);
SRV_ABI_BRIDGE(SYNC_OPS_TAKE_TOKEN,		0xc01c6750u);
SRV_ABI_BRIDGE(SYNC_OPS_FLUSH_TO_TOKEN,		0xc01c6751u);
SRV_ABI_BRIDGE(SYNC_OPS_FLUSH_TO_MOD_OBJ,	0xc01c6752u);
SRV_ABI_BRIDGE(SYNC_OPS_FLUSH_TO_DELTA,		0xc01c6753u);
SRV_ABI_BRIDGE(ALLOC_SYNC_INFO,			0xc01c6754u);
SRV_ABI_BRIDGE(FREE_SYNC_INFO,			0xc01c6755u);

/* Input and output structure sizes the KM handlers copy. */
SRV_ABI_SIZE(PVRSRV_BRIDGE_RETURN, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_COMPAT_CHECK, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ENUMDEVICE, 328);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_ACQUIRE_DEVICEINFO, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ACQUIRE_DEVICEINFO, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_CREATE_DEVMEMCONTEXT, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_CREATE_DEVMEMCONTEXT, 780);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_DESTROY_DEVMEMCONTEXT, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_GET_DEVMEM_HEAPINFO, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_GET_DEVMEM_HEAPINFO, 776);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_ALLOCDEVICEMEM, 48);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ALLOCDEVICEMEM, 88);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_FREEDEVICEMEM, 72);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_FREEDEVICEMEM, 4);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MHANDLE_TO_MMAP_DATA, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_MHANDLE_TO_MMAP_DATA, 20);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_CONNECT_SERVICES, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_CONNECT_SERVICES, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MAP_DEV_MEMORY, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_MAP_DEV_MEMORY, 88);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_UNMAP_DEV_MEMORY, 88);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_EXPORTDEVICEMEM, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_EXPORTDEVICEMEM, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_RELEASE_MMAP_DATA, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_RELEASE_MMAP_DATA, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MAP_ION_HANDLE, 60);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_MAP_ION_HANDLE, 96);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_UNMAP_ION_HANDLE, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MAPPHYSTOUSERSPACE, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_MAPPHYSTOUSERSPACE, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_UNMAPPHYSTOUSERSPACE, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_GET_MISC_INFO, 152);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_GET_MISC_INFO, 152);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MAP_DEVICECLASS_MEMORY, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_MAP_DEVICECLASS_MEMORY, 96);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_UNMAP_DEVICECLASS_MEMORY, 88);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_ENUMCLASS, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ENUMCLASS, 72);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_OPEN_DISPCLASS_DEVICE, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_OPEN_DISPCLASS_DEVICE, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_CLOSE_DISPCLASS_DEVICE, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_ENUM_DISPCLASS_FORMATS, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ENUM_DISPCLASS_FORMATS, 48);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_ENUM_DISPCLASS_DIMS, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ENUM_DISPCLASS_DIMS, 128);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_GET_DISPCLASS_INFO, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_GET_DISPCLASS_INFO, 80);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_CREATE_DISPCLASS_SWAPCHAIN, 56);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_CREATE_DISPCLASS_SWAPCHAIN, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_DESTROY_DISPCLASS_SWAPCHAIN, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SET_DISPCLASS_RECT, 28);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SET_DISPCLASS_COLOURKEY, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_GET_DISPCLASS_BUFFERS, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_GET_DISPCLASS_BUFFERS, 40);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SWAP_DISPCLASS_TO_BUFFER, 536);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SWAP_DISPCLASS_TO_BUFFER2, 36);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_SWAP_DISPCLASS_TO_BUFFER2, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SWAP_DISPCLASS_TO_SYSTEM, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_OPEN_BUFFERCLASS_DEVICE, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_OPEN_BUFFERCLASS_DEVICE, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_CLOSE_BUFFERCLASS_DEVICE, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_GET_BUFFERCLASS_INFO, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_GET_BUFFERCLASS_INFO, 84);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_GET_BUFFERCLASS_BUFFER, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_GET_BUFFERCLASS_BUFFER, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_WRAP_EXT_MEMORY, 40);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_WRAP_EXT_MEMORY, 88);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_UNWRAP_EXT_MEMORY, 88);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_INITSRV_DISCONNECT, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_EVENT_OBJECT_WAIT, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_EVENT_OBJECT_OPEN, 56);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_EVENT_OBJECT_OPEN, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_EVENT_OBJECT_CLOSE, 60);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_CREATE_SYNC_INFO_MOD_OBJ, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_DESTROY_SYNC_INFO_MOD_OBJ, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MODIFY_PENDING_SYNC_OPS, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_MODIFY_PENDING_SYNC_OPS, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_MODIFY_COMPLETE_SYNC_OPS, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SYNC_OPS_TAKE_TOKEN, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_SYNC_OPS_TAKE_TOKEN, 16);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SYNC_OPS_FLUSH_TO_TOKEN, 20);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SYNC_OPS_FLUSH_TO_MOD_OBJ, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_SYNC_OPS_FLUSH_TO_DELTA, 12);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_ALLOC_SYNC_INFO, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_OUT_ALLOC_SYNC_INFO, 8);
SRV_ABI_SIZE(PVRSRV_BRIDGE_IN_FREE_SYNC_INFO, 8);

/* Client structures that callers allocate or read field by field. */
SRV_ABI_SIZE(SRV_SERVICES, 8);
SRV_ABI_SIZE(PVRSRV_DEVICE_IDENTIFIER, 20);
SRV_ABI_SIZE(PVRSRV_CONNECTION, 464);
SRV_ABI_OFFSET(PVRSRV_CONNECTION, ui32ProcessID, 4);
SRV_ABI_OFFSET(PVRSRV_CONNECTION, sClientDevData.ui32NumDevices, 8);
SRV_ABI_OFFSET(PVRSRV_CONNECTION, sClientDevData.asDevID, 12);
SRV_ABI_OFFSET(PVRSRV_CONNECTION, sClientDevData.apfnDevConnect, 332);
SRV_ABI_OFFSET(PVRSRV_CONNECTION, sClientDevData.apfnDumpTrace, 396);
SRV_ABI_OFFSET(PVRSRV_CONNECTION, ui32SrvFlags, 460);
SRV_ABI_SIZE(PVRSRV_DEV_DATA, 8);
SRV_ABI_SIZE(PVRSRV_CLIENT_MEM_INFO, 56);
SRV_ABI_OFFSET(PVRSRV_CLIENT_MEM_INFO, psClientSyncInfo, 24);
SRV_ABI_OFFSET(PVRSRV_CLIENT_MEM_INFO, hMappingInfo, 28);
SRV_ABI_OFFSET(PVRSRV_CLIENT_MEM_INFO, hKernelMemInfo, 32);
SRV_ABI_OFFSET(PVRSRV_CLIENT_MEM_INFO, ui64Stamp, 40);
SRV_ABI_OFFSET(PVRSRV_CLIENT_MEM_INFO, uiIonBufferSize, 48);
SRV_ABI_SIZE(PVRSRV_CLIENT_SYNC_INFO, 24);
SRV_ABI_OFFSET(PVRSRV_CLIENT_SYNC_INFO, hMappingInfo, 16);
SRV_ABI_OFFSET(PVRSRV_CLIENT_SYNC_INFO, hKernelSyncInfo, 20);
SRV_ABI_SIZE(PVRSRV_HEAP_INFO, 24);
SRV_ABI_SIZE(PVRSRV_EVENTOBJECT, 56);
SRV_ABI_SIZE(PVRSRV_MISC_INFO, 148);
SRV_ABI_SIZE(PVRSRV_SYNC_TOKEN, 16);
SRV_ABI_SIZE(DISPLAY_FORMAT, 4);
SRV_ABI_SIZE(DISPLAY_DIMS, 12);
SRV_ABI_SIZE(DISPLAY_INFO, 76);
SRV_ABI_SIZE(BUFFER_INFO, 80);
SRV_ABI_SIZE(IMG_RECT, 16);

/* PVRSRV_ERROR values the library returns or tests (servicesext.h). */
_Static_assert(PVRSRV_OK == 0, "PVRSRV_OK");
_Static_assert(PVRSRV_ERROR_OUT_OF_MEMORY == 1, "OUT_OF_MEMORY");
_Static_assert(PVRSRV_ERROR_INVALID_PARAMS == 3, "INVALID_PARAMS");
_Static_assert(PVRSRV_ERROR_INIT_FAILURE == 4, "INIT_FAILURE");
_Static_assert(PVRSRV_ERROR_BAD_MAPPING == 8, "BAD_MAPPING");
_Static_assert(PVRSRV_ERROR_TOOMANYBUFFERS == 18, "TOOMANYBUFFERS");
_Static_assert(PVRSRV_ERROR_NOT_SUPPORTED == 19, "NOT_SUPPORTED");
_Static_assert(PVRSRV_ERROR_RETRY == 24, "RETRY");
_Static_assert(PVRSRV_ERROR_DDK_VERSION_MISMATCH == 25, "DDK_VERSION_MISMATCH");
_Static_assert(PVRSRV_ERROR_UNABLE_GET_FUNC_ADDR == 32, "UNABLE_GET_FUNC_ADDR");
_Static_assert(PVRSRV_ERROR_UNLOAD_LIBRARY_FAILED == 33, "UNLOAD_LIBRARY_FAILED");
_Static_assert(PVRSRV_ERROR_BRIDGE_CALL_FAILED == 34, "BRIDGE_CALL_FAILED");
_Static_assert(PVRSRV_ERROR_UNABLE_TO_CLOSE_SERVICES == 101, "UNABLE_TO_CLOSE_SERVICES");
_Static_assert(PVRSRV_ERROR_TIMEOUT_POLLING_FOR_VALUE == 111, "TIMEOUT_POLLING_FOR_VALUE");
_Static_assert(PVRSRV_ERROR_MUTEX_DESTROY_FAILED == 123, "MUTEX_DESTROY_FAILED");
_Static_assert(PVRSRV_ERROR_HANDLE_INDEX_OUT_OF_RANGE == 149, "HANDLE_INDEX_OUT_OF_RANGE");
_Static_assert(PVRSRV_ERROR_BAD_SYNC_STATE == 182, "BAD_SYNC_STATE");

/* PVRSRVCompatCheckKM compares against these two words. */
_Static_assert(((PVRVERSION_MAJ << 16) | (PVRVERSION_MIN << 8)) == 0x00010E00, "DDK version word");
_Static_assert(PVRVERSION_BUILD == 4081762, "DDK build");
